// <auto-generated />
using System;
using MES_ME.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MES_ME.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316090226_ConfigureCascadeDeleteForAuditLog2")]
    partial class ConfigureCascadeDeleteForAuditLog2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MES_ME.Server.Models.AnnealingBatchPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("plan_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanId"));

                    b.Property<DateTimeOffset?>("ActualEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_end_time");

                    b.Property<DateTimeOffset?>("ActualStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_start_time");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<string>("FurnaceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("furnace_number");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("plan_name");

                    b.Property<DateTimeOffset?>("ScheduledEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_end_time");

                    b.Property<DateTimeOffset?>("ScheduledStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PlanId");

                    b.ToTable("annealing_batch_plans", "mes");
                });

            modelBuilder.Entity("MES_ME.Server.Models.AnnealingBatchPlanSheet", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("link_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LinkId"));

                    b.Property<string>("ExecutionComment")
                        .HasColumnType("text")
                        .HasColumnName("execution_comment");

                    b.Property<string>("MatId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("matid");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_id");

                    b.Property<int?>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<string>("StatusOverride")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status_override");

                    b.HasKey("LinkId");

                    b.HasIndex("MatId");

                    b.HasIndex("PlanId");

                    b.ToTable("annealing_batch_plan_sheets", "mes");
                });

            modelBuilder.Entity("MES_ME.Server.Models.AnnealingPlan", b =>
                {
                    b.Property<string>("PlanId")
                        .HasColumnType("text")
                        .HasColumnName("plan_id");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("actual_end_time");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("actual_start_time");

                    b.Property<int>("CassettesCount")
                        .HasColumnType("integer")
                        .HasColumnName("cassettes_count");

                    b.Property<string>("FurnaceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("furnace_number");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("plan_name");

                    b.Property<DateTime?>("ScheduledEndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("scheduled_end_time");

                    b.Property<DateTime?>("ScheduledStartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("scheduled_start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalWeightKg")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_weight_kg");

                    b.HasKey("PlanId");

                    b.ToTable("annealing_plans", "mes");
                });

            modelBuilder.Entity("MES_ME.Server.Models.AnnealingSchedule", b =>
                {
                    b.Property<int>("AnnealingPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("annealing_plan_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnnealingPlanId"));

                    b.Property<DateTimeOffset?>("ActualEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_end_time");

                    b.Property<DateTimeOffset?>("ActualStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_start_time");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<string>("ExecutedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("executed_by");

                    b.Property<string>("ExecutionComment")
                        .HasColumnType("text")
                        .HasColumnName("execution_comment");

                    b.Property<string>("FurnaceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("furnace_number");

                    b.Property<string>("FurnaceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("furnace_type");

                    b.Property<string>("MatId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("matid");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("ScheduledEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_end_time");

                    b.Property<DateTimeOffset?>("ScheduledStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start_time");

                    b.Property<int?>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AnnealingPlanId");

                    b.HasIndex("MatId");

                    b.ToTable("annealing_schedule", "mes");
                });

            modelBuilder.Entity("MES_ME.Server.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MES_ME.Server.Models.Cassette", b =>
                {
                    b.Property<string>("CassetteId")
                        .HasColumnType("text")
                        .HasColumnName("cassette_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrentMasterId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("current_master_id");

                    b.Property<string>("CurrentOperatorId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("current_operator_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("CassetteId");

                    b.ToTable("cassettes", "mes");
                });

            modelBuilder.Entity("MES_ME.Server.Models.CassettePlanLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CassetteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cassette_id");

                    b.Property<int?>("CassetteNumberInPlan")
                        .HasColumnType("integer")
                        .HasColumnName("cassette_number_in_plan");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan_id");

                    b.HasKey("Id");

                    b.HasIndex("CassetteId");

                    b.HasIndex("PlanId", "CassetteId")
                        .IsUnique();

                    b.ToTable("cassette_annealing_plan_links", "mes");
                });

            modelBuilder.Entity("MES_ME.Server.Models.CassetteStatusLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("CassetteId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cassette_id");

                    b.Property<DateTimeOffset>("ChangeTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("change_timestamp");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("changed_by");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("new_status");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("old_status");

                    b.HasKey("LogId");

                    b.ToTable("cassette_status_log", "mes");
                });

            modelBuilder.Entity("MES_ME.Server.Models.InputDatum", b =>
                {
                    b.Property<string>("MatId")
                        .HasColumnType("text")
                        .HasColumnName("matid");

                    b.Property<decimal?>("ActualNetWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("actual_net_weight_kg");

                    b.Property<decimal?>("ActualWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("actual_weight");

                    b.Property<DateTime?>("BallisticsSampleSendDate1")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ballistics_sample_send_date_1");

                    b.Property<DateTime?>("BallisticsSampleSendDate2")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ballistics_sample_send_date_2");

                    b.Property<DateTime?>("BallisticsSampleSendDate3")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ballistics_sample_send_date_3");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text")
                        .HasColumnName("batch_number");

                    b.Property<decimal?>("CertificateNetWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("certificate_net_weight_kg");

                    b.Property<string>("CertificateNumber")
                        .HasColumnType("text")
                        .HasColumnName("certificate_number");

                    b.Property<string>("CertificateNumber2")
                        .HasColumnType("text")
                        .HasColumnName("certificate_number_2");

                    b.Property<string>("CommercialOrderNumber")
                        .HasColumnType("text")
                        .HasColumnName("commercial_order_number");

                    b.Property<string>("Defect")
                        .HasColumnType("text")
                        .HasColumnName("defect");

                    b.Property<decimal?>("FlatnessMm")
                        .HasColumnType("numeric")
                        .HasColumnName("flatness_mm");

                    b.Property<string>("GpAcceptanceStatusWeight")
                        .HasColumnType("text")
                        .HasColumnName("gp_acceptance_status_weight");

                    b.Property<DateTime?>("GpVpPresentationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("gp_vp_presentation_date");

                    b.Property<DateTime?>("HardnessSampleSendDate1")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("hardness_sample_send_date_1");

                    b.Property<DateTime?>("HardnessSampleSendDate2")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("hardness_sample_send_date_2");

                    b.Property<DateTime?>("HardnessSampleSendDate3")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("hardness_sample_send_date_3");

                    b.Property<string>("IgkLink")
                        .HasColumnType("text")
                        .HasColumnName("igk_link");

                    b.Property<string>("Marking")
                        .HasColumnType("text")
                        .HasColumnName("marking");

                    b.Property<string>("MeltNumber")
                        .HasColumnType("text")
                        .HasColumnName("melt_number");

                    b.Property<DateTime?>("MetallographySampleSendDate1")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("metallography_sample_send_date_1");

                    b.Property<DateTime?>("MetallographySampleSendDate2")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("metallography_sample_send_date_2");

                    b.Property<string>("MmkClaimReason")
                        .HasColumnType("text")
                        .HasColumnName("mmk_claim_reason");

                    b.Property<decimal?>("NonReturnScrap")
                        .HasColumnType("numeric")
                        .HasColumnName("non_return_scrap");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("NpAcceptanceStatusWeight")
                        .HasColumnType("text")
                        .HasColumnName("np_acceptance_status_weight");

                    b.Property<string>("NpAct")
                        .HasColumnType("text")
                        .HasColumnName("np_act");

                    b.Property<string>("NpDecision")
                        .HasColumnType("text")
                        .HasColumnName("np_decision");

                    b.Property<string>("OrderLink")
                        .HasColumnType("text")
                        .HasColumnName("order_link");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.Property<string>("PackNumber")
                        .HasColumnType("text")
                        .HasColumnName("pack_number");

                    b.Property<string>("PackSystemNumber")
                        .HasColumnType("text")
                        .HasColumnName("pack_system_number");

                    b.Property<decimal?>("PostShipDiff")
                        .HasColumnType("numeric")
                        .HasColumnName("post_ship_diff");

                    b.Property<DateTime?>("QuenchingDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("quenching_date");

                    b.Property<string>("QuenchingStatus")
                        .HasColumnType("text")
                        .HasColumnName("quenching_status");

                    b.Property<decimal?>("RawMaterialKg")
                        .HasColumnType("numeric")
                        .HasColumnName("raw_material_kg");

                    b.Property<DateTime?>("RepeatedToDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("repeated_to_date");

                    b.Property<DateTime?>("RollDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("roll_date");

                    b.Property<string>("SampleCardsSelection")
                        .HasColumnType("text")
                        .HasColumnName("sample_cards_selection");

                    b.Property<string>("SampleNumberVk")
                        .HasColumnType("text")
                        .HasColumnName("sample_number_vk");

                    b.Property<string>("ScrapAcceptanceStatusWeight")
                        .HasColumnType("text")
                        .HasColumnName("scrap_acceptance_status_weight");

                    b.Property<string>("SheetDimensions")
                        .HasColumnType("text")
                        .HasColumnName("sheet_dimensions");

                    b.Property<string>("SheetNumber")
                        .HasColumnType("text")
                        .HasColumnName("sheet_number");

                    b.Property<decimal?>("SheetWeightAfterToStorageKg")
                        .HasColumnType("numeric")
                        .HasColumnName("sheet_weight_after_to_storage_kg");

                    b.Property<decimal?>("SheetWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("sheet_weight_kg");

                    b.Property<int?>("SheetsCount")
                        .HasColumnType("integer")
                        .HasColumnName("sheets_count");

                    b.Property<DateTime?>("ShipmentDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("shipment_date");

                    b.Property<decimal?>("ShippedSheetsWeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("shipped_sheets_weight_kg");

                    b.Property<string>("ShortOrderNumber")
                        .HasColumnType("text")
                        .HasColumnName("short_order_number");

                    b.Property<string>("SlabNumber")
                        .HasColumnType("text")
                        .HasColumnName("slab_number");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SteelGrade")
                        .HasColumnType("text")
                        .HasColumnName("steel_grade");

                    b.Property<string>("TestingStatus")
                        .HasColumnType("text")
                        .HasColumnName("testing_status");

                    b.Property<decimal?>("Trimming")
                        .HasColumnType("numeric")
                        .HasColumnName("trimming");

                    b.HasKey("MatId");

                    b.ToTable("inputdata", "mes");
                });

            modelBuilder.Entity("MES_ME.Server.Models.LoginLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoginLogs");
                });

            modelBuilder.Entity("MES_ME.Server.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Просмотр главной страницы",
                            Name = "view_dashboard"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Просмотр списка пользователей",
                            Name = "view_users"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Управление пользователями",
                            Name = "manage_users"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Управление ролями",
                            Name = "manage_roles"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Просмотр панели управления",
                            Name = "view_control_panel"
                        });
                });

            modelBuilder.Entity("MES_ME.Server.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Полный доступ",
                            Name = "superadmin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Доступ к разработке",
                            Name = "developer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Мастер производства",
                            Name = "master"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Оператор",
                            Name = "operator"
                        });
                });

            modelBuilder.Entity("MES_ME.Server.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("MES_ME.Server.Models.SheetCassetteLink", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("link_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LinkId"));

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("assigned_by");

                    b.Property<string>("CassetteId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cassette_id");

                    b.Property<string>("MatId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("matid");

                    b.HasKey("LinkId");

                    b.HasIndex("CassetteId");

                    b.HasIndex("MatId")
                        .IsUnique();

                    b.ToTable("sheet_cassette_links", "mes");
                });

            modelBuilder.Entity("MES_ME.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MES_ME.Server.Models.AnnealingBatchPlanSheet", b =>
                {
                    b.HasOne("MES_ME.Server.Models.InputDatum", "Sheet")
                        .WithMany()
                        .HasForeignKey("MatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MES_ME.Server.Models.AnnealingBatchPlan", "BatchPlan")
                        .WithMany("LinkedSheets")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatchPlan");

                    b.Navigation("Sheet");
                });

            modelBuilder.Entity("MES_ME.Server.Models.AnnealingSchedule", b =>
                {
                    b.HasOne("MES_ME.Server.Models.InputDatum", "Sheet")
                        .WithMany()
                        .HasForeignKey("MatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sheet");
                });

            modelBuilder.Entity("MES_ME.Server.Models.AuditLog", b =>
                {
                    b.HasOne("MES_ME.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MES_ME.Server.Models.CassettePlanLink", b =>
                {
                    b.HasOne("MES_ME.Server.Models.Cassette", null)
                        .WithMany("CassettePlanLinks")
                        .HasForeignKey("CassetteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MES_ME.Server.Models.LoginLog", b =>
                {
                    b.HasOne("MES_ME.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MES_ME.Server.Models.RolePermission", b =>
                {
                    b.HasOne("MES_ME.Server.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MES_ME.Server.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MES_ME.Server.Models.SheetCassetteLink", b =>
                {
                    b.HasOne("MES_ME.Server.Models.Cassette", "Cassette")
                        .WithMany("LinkedSheets")
                        .HasForeignKey("CassetteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MES_ME.Server.Models.InputDatum", "Sheet")
                        .WithMany()
                        .HasForeignKey("MatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cassette");

                    b.Navigation("Sheet");
                });

            modelBuilder.Entity("MES_ME.Server.Models.User", b =>
                {
                    b.HasOne("MES_ME.Server.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MES_ME.Server.Models.AnnealingBatchPlan", b =>
                {
                    b.Navigation("LinkedSheets");
                });

            modelBuilder.Entity("MES_ME.Server.Models.Cassette", b =>
                {
                    b.Navigation("CassettePlanLinks");

                    b.Navigation("LinkedSheets");
                });

            modelBuilder.Entity("MES_ME.Server.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("MES_ME.Server.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
