# --- Stage 1: Build (теперь это просто копирование) ---
FROM nginx:alpine AS final
# Копируем нашу конфигурацию nginx
COPY nginx.conf /etc/nginx/nginx.conf
# Копируем уже собранную папку build из хоста (в контекст сборки)
COPY build /usr/share/nginx/html
EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"] # Не обязательно, nginx запускается по умолчанию