events {
  worker_connections  1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  server {
    listen       80;
    server_name  localhost; # или ваш домен, если есть

    # Корень, куда отдаются статические файлы React
    root   /usr/share/nginx/html;
    index  index.html;

    # Обработка маршрутов React Router (если используется)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Проксирование запросов к API на бэкенд
    # Все запросы, начинающиеся с /api, будут перенаправлены на сервис бэкенда
    location /api {
         proxy_pass http://backend-mesmeserver-1:80; # ЗАМЕНИТЬ <имя_контейнера_бэкенда>
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Если у вас есть другие эндпоинты, которые нужно проксировать, добавьте их аналогично
    # location /auth {
    #      proxy_pass http://<имя_контейнера_бэкенда>:80;
    #      proxy_set_header Host $host;
    #      ...
    # }
  }
}